/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Chart: typeof import('./src/components/chart/index.vue')['default']
    CoinYang: typeof import('./src/components/coin/coinYang.vue')['default']
    CoinYin: typeof import('./src/components/coin/coinYin.vue')['default']
    copy: typeof import('./src/components/coin/coinYang copy.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanSwitch: typeof import('vant/es')['Switch']
    Xiang: typeof import('./src/components/xiang/xiang.vue')['default']
  }
}
